cmpPrice/cmpPrice/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('showingPage.urls', namespace='showingPage')),
]

cmpPrice/showingPage/urls.py
from django.urls import path
from . import views

app_name = 'showingPage'
urlpatterns = [
    path('',views.home,name='home'),
    path('/cmpprice/<str:id>/',views.cmpPrice,name='cmpPrice'),
    ]

cmpPrice/showingPage/models.py
from django.db import models

# Create your models here.

cmpPrice/showingPage/views.py
from django.shortcuts import render
from .spider.jdPro import jdSearch
from .spider.taobaoPro import tbSearch
from .spider.zggjtsg import bookdetails
from .spider.amazon import amazon
from .spider.dangdang import dangdang
# Create your views here.

def home(request):
    try:
        input = request.POST.get('search')
    except:
        input='python'
    if not input:
        context = {'JD_goodslist': [], 'TB_goodslist':[]}
        return render(request,'showingPage/home.html',context)

    try:
        n = int(request.POST.get('number'))
    except:
        n=10
    if n<=0:
        n=10

    jd=jdSearch(input,n)
    tb=tbSearch(input,n)
    context={'JD_goodslist':jd,'TB_goodslist':tb}
    return render(request,'showingPage/home.html',context)

def cmpPrice(request,id):
    jd = jdSearch(id,5)
    a=amazon(id)
    dd=dangdang(id)
    imgs=a[0]['good_pic']
    if imgs==None:
        imgs=jd[0]['good_pic']
    s=bookdetails(id)
    [name, author, publisher, abstract]=s
    result=a+jd+dd
    context = {'result': result,
               'publisher':publisher,
               'ISBN':id,
               'name':name,
               'author':author,
               'abstract':abstract,
               'imgs':imgs
               }
    return render(request, 'showingPage/book_detail.html', context)

cmpPrice/templates/back_to_top.html
<!-- https://ezbox.idv.tw/131/back-to-top-button-without-images -->

<button type="button" id="BackTop" class="toTop-arrow"></button>

<script>
$(function(){
	$('#BackTop').click(function(){
		$('html,body').animate({scrollTop:0}, 333);
	});
	$(window).scroll(function() {
		if ( $(this).scrollTop() > 300 ){
			$('#BackTop').fadeIn(222);
		} else {
			$('#BackTop').stop().fadeOut(222);
		}
	}).scroll();
});
</script>
<style>
    .toTop-arrow {
	width: 2.5rem;
	height: 2.5rem;
	padding: 0;
	margin: 0;
	border: 0;
	border-radius: 33%;
	opacity: 0.6;
	background: #000;
	cursor: pointer;
	position:fixed;
	right: 1rem;
	bottom: 1rem;
	display: none;
}
.toTop-arrow::before, .toTop-arrow::after {
	width: 18px;
	height: 5px;
	border-radius: 3px;
	background: #f90;
	position: absolute;
	content: "";
}
.toTop-arrow::before {
	transform: rotate(-45deg) translate(0, -50%);
	left: 0.5rem;
}
.toTop-arrow::after {
	transform: rotate(45deg) translate(0, -50%);
	right: 0.5rem;
}
.toTop-arrow:focus {outline: none;}


/* 48px */
.toTop-arrow {
	width: 3rem;
	height: 3rem;
	padding: 0;
	margin: 0;
	border: 0;
	border-radius: 33%;
	opacity: 0.6;
	background: #000;
	cursor: pointer;
	position:fixed;
	right: 1rem;
	bottom: 1rem;
	display: none;
}
.toTop-arrow::before, .toTop-arrow::after {
	width: 25px;
	height: 6px;
	border-radius: 3px;
	background: #f90;
	position: absolute;
	content: "";
}
.toTop-arrow::before {
	transform: rotate(-45deg) translate(0, -50%);
	left: 0.42rem;
}
.toTop-arrow::after {
	transform: rotate(45deg) translate(0, -50%);
	right: 0.42rem;
}
.toTop-arrow:focus {outline: none;}

/* 56px */
.toTop-arrow {
	width: 3.5rem;
	height: 3.5rem;
	padding: 0;
	margin: 0;
	border: 0;
	border-radius: 33%;
	opacity: 0.6;
	background: #000;
	cursor: pointer;
	position:fixed;
	right: 1rem;
	bottom: 1rem;
	display: none;
}
.toTop-arrow::before, .toTop-arrow::after {
	width: 31px;
	height: 7px;
	border-radius: 3px;
	background: #f90;
	position: absolute;
	content: "";
}
.toTop-arrow::before {
	transform: rotate(-45deg) translate(0, -50%);
	left: 0.4rem;
}
.toTop-arrow::after {
	transform: rotate(45deg) translate(0, -50%);
	right: 0.4rem;
}
.toTop-arrow:focus {outline: none;}
</style>

cmpPrice/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <title>
        {% block title %}
        {% endblock %}
    </title>
</head>

<body>

    <div class="jumbotron">
        <div class="container">
        {% include 'header.html' %}
        {% block content %}
        {% endblock %}
    </div></div>
</body>

    {% include 'back_to_top.html' %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>

</html>

cmpPrice/templates/header.html
<h1> Welcome to Searching and Compare System</h1>

cmpPrice/templates/showingPage/book_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    price cmp details
{% endblock title %}
{% block content %}

<p></p>
<div class="container">
  <div class="row">
    <div class="col">
      <img src="{{imgs}}" alt="no pic" height="200" width="200"><br>
        <br>
        <p><b>{{name}}</b></p>
        <p><b>ISBN </b><span>{{ISBN}}</span></p>
        <p><b>{{author}}</b></p>
        <p><b>{{publisher}}</b></p>
        <p>{{abstract}}</p>
    </div>
    <div class="col">
        <table class="table table-striped">
          <thead>
            <tr>
                <th scope="col">Sold by</th>
                <th scope="col">Price</th>
                <th scope="col">Comment</th>
                <th scope="col">Rate</th>
                <th scope="col">shopping link?</th>
            </tr>
          </thead>
          <tbody>
          {% for good in result%}
            <tr>
                <td style="vertical-align: middle !important;text-align: center;">{{good.good_from}}</td>
                <td style="vertical-align: middle !important;text-align: center;">{{good.good_price_unit}}{{good.good_price}}</td>
                <td style="vertical-align: middle !important;text-align: center;">{{good.good_num_comment}}</td>
                <td style="vertical-align: middle !important;text-align: center;">{{good.good_comment_rate}}</td>
                <td style="vertical-align: middle !important;text-align: center;"><a href="{{good.good_url}}">want to buy?</a><br></td>
            </tr>
          {%endfor%}
          </tbody>
        </table>
    </div>

  </div>
</div>

{% endblock content %}

cmpPrice/templates/showingPage/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    choose goods
{% endblock title %}
{% block content %}

<div class="">
        <form class="form-inline my-2 my-lg-0" action="{% url 'showingPage:home' %}" method="POST">
          {%csrf_token%}
            <input type="search"
                class="form-control mr-sm-2"
                name="search"
                placeholder="search..."
                required
            >
            <input type="search"
                class="form-control mr-sm-2"
                name="number"
                placeholder="Qty searching..."
                required
            >
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>

<div class="row">
        <div class="col">
            <h5>The most <b><em>popular</em></b> from JD</h5>
            <div>
    {% for good in JD_goodslist%}
    <div class="row">
        <div class="col-sm-4">
            <img src="{{good.good_pic}}" alt="no pic" class="img-thumbnail">
        </div>
        <div class="col-sm-8">
            <a href="{{good.good_url}}">{{good.good_name}}</a><br>
            <em>ISBN </em><a href="{% url 'showingPage:cmpPrice' good.good_ISBN %}">{{good.good_ISBN}}</a><br>
            <em>Price </em><span style="color:red;">{{good.good_price_unit}}{{good.good_price}}</span><br>
            <em>Comment </em><span style="color:green;">{{good.good_num_comment}}</span><br>
            <em>Rate </em><span style="color:green;">{{good.good_comment_rate}}</span><br>
        </div>
    </div>
    <br>
    {% endfor %}
</div>
        </div>
        <div class="col">
            <h5>The most <b><em>popular</em></b> from taobao</h5>
            <div>
                {% for good in TB_goodslist%}
                <div class="row">
                    <div class="col-sm-4">
                        <img src="{{good.good_pic}}" alt="no pic" class="img-thumbnail">
                    </div>
                    <div class="col-sm-8">
                        <a href="{{good.good_url}}">{{good.good_name}}</a><br>
                        <em>ISBN </em><a href="{% url 'showingPage:cmpPrice' good.good_ISBN %}">{{good.good_ISBN}}</a><br>
                        <em>Price </em><span style="color:red;">￥{{good.good_price}}</span><br>
                        <em>Comment </em><span style="color:green;">{{good.good_num_comment}}</span><br>
                        <em>Rate </em><span style="color:green;">{{good.good_comment_rate}}</span><br>
                    </div>
                </div>
                <br>
                {% endfor %}
            </div>
        </div>
</div>
{% endblock content %}